<Project>
  <PropertyGroup>
    <Version>$([System.IO.File]::ReadAllText('$(MSBuildThisFileDirectory)VERSION').Trim())</Version>
    <AssemblyVersion>$(Version).0</AssemblyVersion>
    <FileVersion>$(Version).0</FileVersion>
    <InformationalVersion>$(Version)</InformationalVersion>
  </PropertyGroup>
</Project>
